CFLAGS:= -std=c99
cipher: dna
	gcc dna.o -o dna -std=c99
dna.o: dna.c

#
#test: test1 test2 test3 test4 test5 test6
#test1:
#	./cipher 1 5 data.txt data.out
#test2:
#	./cipher 2 5 data.out data.bak
#test3:
#	./cipher 1 437 data.txt multiEncrypt.out
#test4:
#	./cipher 2 437 multiEncrypt.out multiEncrypt.bak
#test5:
#	diff -s data.txt data.bak
#test6:
#	diff -s data.txt multiEncrypt.bak
